- hosts: magento-servers
  remote_user: ubuntu
  become: true
  tasks:
    - name: update
      apt: 
        update_cache: yes
    - name: Install Nginx
      apt: 
        name: nginx 
        state: latest

    
      
    - name: copy nginx configuration
      template:
        src: nginx.conf
        dest: /etc/nginx/sites-available/magento
      notify:
        - restart nginx

    # Nginx will not use the configuration files found in /etc/nginx/sites-available directory unless they are linked to the sites-enabled directory
    - name: Create Symbolic Link
      file:
        src: /etc/nginx/sites-available/magento
        dest: /etc/nginx/sites-enabled/magento
        state: link

    - name: Start Nginx Service
      service:
        name: nginx
        state: started
        enabled: true


    - name: Install snapd
      apt: 
        name: snapd
        state: latest

    - name: Install certbot
      snap:
        name: certbot
        classic: yes

    - name: Create Symbolic Link
      file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link

    - name: Create letsencrypt certificate
      shell: certbot --nginx -d www.nouran-task.xyz
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: 
        name: nginx 
        state: reloaded