- hosts: magento-servers
  remote_user: ubuntu
  become: true
  tasks:
  - name: Install Redis
    apt: 
      name: redis-server 
      state: latest
  # - name: Configure Magento to use Redis
  #     template:
  #       src: redis.php
  #       dest: /var/www/html/magento2/app/etc/env.php
  - name: Setup redis
    shell: |
      php bin/magento setup:config:set --cache-backend=redis --cache-backend-redis-server=127.0.0.1 --cache-backend-redis-db=0
      php bin/magento setup:config:set --page-cache=redis --page-cache-redis-server=127.0.0.1 --page-cache-redis-db=1
      php bin/magento setup:config:set --session-save=redis --session-save-redis-host=127.0.0.1 --session-save-redis-log-level=3 --session-save-redis-max-concurrency=12 --session-save-redis-db=2
    args:
      chdir: /var/www/html/magento2
    notify:
        - restart redis

  handlers:
    - name: restart redis
      service: 
        name: redis-server 
        state: reloaded
  